vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        duck_image:
            uri_prefix: /images/ducks
            upload_destination: '%kernel.project_dir%/public/uploads/images/ducks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
